/** Canonical AFTER HOURS brand language. These strings are protected from UI translation. */
export const AFTER_HOURS_BRAND = Object.freeze({
  name: "AFTER HOURS",
  teaserSignoff: "AFTER HOURS · ENTER AFTER DARK",
  primaryPunchline: "YOUR RULES. YOUR LIMITS. YOUR EXPERIENCE.",
  privateExperience: "A PRIVATE 18+ EXPERIENCE",
  enter: "ENTER AFTER HOURS",
  startExperience: "START EXPERIENCE",
  tryFreeDemo: "TRY FREE DEMO",
  watchTrailer: "WATCH TRAILER",
  randomKink: "RANDOM KINK",
  surpriseMe: "SURPRISE ME",
  dailyKink: "DAILY KINK",
  ranks: [
    "CURIOUS",
    "TEASE",
    "PLAYTHING",
    "SUBMISSIVE",
    "BRAT",
    "TOY",
    "PET",
    "THRALL",
    "DEVOTEE",
    "OBEDIENT",
    "ENTHRALLED",
    "COLLARED",
    "OWNED",
    "DEVOTED",
    "DARK DEVOTION",
  ],
  terms: [
    "STORY", "RANDOM", "SURPRISE", "CUSTOM", "BOSS", "THE GUIDE",
    "CHARACTER CREATION", "RANKS & XP", "ORACLE", "EXPERIENCES",
    "TIMER", "PAUSE", "PASS", "STOP", "CONTINUE", "RADIO",
    "DAILY AFTER HOURS", "ACHIEVEMENTS & COLLECTION", "THE AFTER HOURS ARCHIVE",
    "AFTERCARE MODE", "PRIVACY MODE", "HELP CENTER & SUPPORT",
    "AFTER HOURS INBOX", "CONTROL ROOM",
  ],
} as const);
