import React,{useEffect,useMemo,useState}from"react";import{createRoot}from"react-dom/client";import{Shield,Lock,Play,Pause,RotateCcw,ChevronRight,User,Settings,Home,Timer,CheckCircle2,AlertTriangle,Square,Activity,LogOut}from"lucide-react";import"./styles.css";
type Screen="home"|"game"|"profile"|"admin";
const rounds=[{title:"De Eerste Stap",text:"Neem een moment. Spreek samen af wat vandaag wel, niet en misschien is.",time:180},{title:"De Richting",text:"Kies één opdracht die past bij jullie afgesproken grenzen. Communiceer helder.",time:240},{title:"De Verdieping",text:"Blijf aanwezig, check in en gebruik jullie afgesproken stopwoord wanneer nodig.",time:300}];
function App(){const[age,setAge]=useState(false);const[consent,setConsent]=useState(false);const[screen,setScreen]=useState<Screen>("home");const[round,setRound]=useState(0);const[running,setRunning]=useState(false);const[seconds,setSeconds]=useState(rounds[0].time);const[safety,setSafety]=useState<"green"|"amber"|"red">("green");
useEffect(()=>{if(!running)return;const id=setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000);return()=>clearInterval(id)},[running]);
const progress=Math.round(((round+1)/rounds.length)*100);const clock=useMemo(()=>String(Math.floor(seconds/60)).padStart(2,"0")+":"+String(seconds%60).padStart(2,"0"),[seconds]);
const start=()=>{setAge(true);setConsent(true)};const next=()=>{if(round<rounds.length-1){const n=round+1;setRound(n);setSeconds(rounds[n].time);setRunning(false)}else setScreen("home")};const reset=()=>{setSeconds(rounds[round].time);setRunning(false)};
if(!age)return <div className="gate"><div className="mark">AH</div><span className="eyebrow">PRIVATE EXPERIENCE · 18+</span><h1>AFTER<br/><i>HOURS</i></h1><p>Een premium interactieve ervaring voor volwassenen. Bewust. Afgesproken. Veilig.</p><button onClick={start}>Ik ben 18+ <ChevronRight/></button><small>Je toegang bevestigt dat je 18 jaar of ouder bent.</small></div>;
return <div className="app"><header><button className="wordmark" onClick={()=>setScreen("home")}>AFTER <i>HOURS</i></button><div className="status"><span></span> privé sessie</div></header>
{screen==="home"&&<main><section className="hero"><span className="eyebrow">JULLIE AVOND</span><h2>Take your time.</h2><p>Een zorgvuldig opgebouwde ervaring waarin toestemming, communicatie en grenzen altijd voorop staan.</p><div className="safety"><Shield/><div><strong>Veiligheidscheck</strong><span>Jullie grenzen zijn actief</span></div><b>{safety==="green"?"GOED":"CHECK"}</b></div></section><section><div className="sectionhead"><span>THE 60-MINUTE EXPERIENCE</span><em>03 ROUNDS</em></div><article className="gamecard"><div><span className="number">01</span><h3>De Nacht Begint</h3><p>Drie begeleide rondes. Jullie bepalen tempo, grenzen en stopmoment.</p></div><button onClick={()=>setScreen("game")}><Play fill="currentColor"/></button></article></section><section className="grid"><button className="tile" onClick={()=>setScreen("profile")}><User/><span>Profiel</span><small>Night Walker · Level 4</small></button><button className="tile" onClick={()=>setSafety(safety==="green"?"amber":"green")}><Activity/><span>Consent</span><small>{safety==="green"?"Actief en bevestigd":"Check opnieuw"}</small></button><button className="tile" onClick={()=>setScreen("admin")}><Settings/><span>Control room</span><small>Beheer & instellingen</small></button></section></main>}
{screen==="game"&&<main><div className="game-top"><button onClick={()=>setScreen("home")}><LogOut/></button><span>ROUND {String(round+1).padStart(2,"0")} / 03</span></div><div className="progress"><span style={{width:progress+"%"}}/></div><section className="round"><span className="eyebrow">AFTER HOURS</span><h2>{rounds[round].title}</h2><p>{rounds[round].text}</p><div className="timer"><Timer/><strong>{clock}</strong><small>TIJD OVER</small></div><div className="actions"><button className="gold" onClick={()=>setRunning(!running)}>{running?<Pause/>:<Play/>}{running?"Pauzeren":"Start ronde"}</button><button onClick={reset}><RotateCcw/> Reset</button><button className="stop" onClick={()=>{setRunning(false);setScreen("home")}}><Square/> Stop sessie</button></div><div className="consent"><CheckCircle2/><div><strong>Consent bevestigd</strong><span>Jullie kunnen op elk moment stoppen.</span></div></div></section><button className="next" onClick={next}>{round===2?"Afronden":"Volgende ronde"} <ChevronRight/></button></main>}
{screen==="profile"&&<main><section className="profile"><div className="avatar">N4</div><span className="eyebrow">YOUR PROFILE</span><h2>Night Walker</h2><p>Level 4 · 680 XP</p><div className="xp"><span style={{width:"68%"}}/></div><div className="stats"><div><b>04</b><small>LEVEL</small></div><div><b>12</b><small>SESSIES</small></div><div><b>680</b><small>XP</small></div></div></section><button className="back" onClick={()=>setScreen("home")}>← Terug</button></main>}
{screen==="admin"&&<main><section className="admin"><span className="eyebrow">CONTROL ROOM</span><h2>Beheer</h2><div className="adminrow"><Activity/><div><b>Sessie status</b><span>Actief · alle systemen normaal</span></div><i/></div><div className="adminrow"><Shield/><div><b>Consent</b><span>Vereist vóór elke sessie</span></div><i/></div><div className="adminrow"><Lock/><div><b>Privacy</b><span>Lokale sessiedata</span></div><i/></div></section><button className="back" onClick={()=>setScreen("home")}>← Terug</button></main>}
<nav><button onClick={()=>setScreen("home")}><Home/><span>Home</span></button><button onClick={()=>setScreen("game")}><Timer/><span>Experience</span></button><button onClick={()=>setScreen("profile")}><User/><span>Profiel</span></button></nav>
{!consent&&<div/>}</div>}
createRoot(document.getElementById("root")!).render(<App/>);