import React, { useMemo, useState } from "react";
import { ArrowRight, Check, Copy, Heart, Shuffle, ShieldCheck } from "lucide-react";

type PromptKind = "Kinky opdrachten" | "Kinky vragen" | "Vanille & verbinding" | "Aftercare";
type PromptItem = { id: string; kind: PromptKind; intensity: "Zacht" | "Stevig in taal" | "Reflectie"; title: string; text: string; note?: string };

const prompts: PromptItem[] = [
  {id:"k01",kind:"Kinky opdrachten",intensity:"Zacht",title:"De bewuste buiging",text:"Als je daar oprecht zin in hebt, neem dan een houding aan die voor jou nederigheid of toewijding symboliseert. Houd die alleen zolang het prettig voelt.",note:"Alleen op uitnodiging en zonder fysieke druk."},
  {id:"k02",kind:"Kinky opdrachten",intensity:"Stevig in taal",title:"De formele toestemming",text:"Vraag met woorden om toestemming voor één vooraf besproken, niet-risicovolle handeling. Wacht op een duidelijk ja en accepteer een nee zonder discussie."},
  {id:"k03",kind:"Kinky opdrachten",intensity:"Zacht",title:"Ogen op mij",text:"Maak alleen oogcontact als dat fijn voelt. Vertel daarna in één zin wat je op dit moment nodig hebt."},
  {id:"k04",kind:"Kinky opdrachten",intensity:"Stevig in taal",title:"De opdracht",text:"Geef een korte, respectvolle opdracht binnen de afgesproken grenzen, bijvoorbeeld: 'Leg je telefoon weg en kies een nummer dat bij je stemming past.' De ander mag altijd passen."},
  {id:"k05",kind:"Kinky opdrachten",intensity:"Zacht",title:"Het ritueel",text:"Kies samen een klein beginritueel: een buiging, een afgesproken aanspreekvorm of een moment stilte. Spreek vooraf af dat het optioneel blijft."},
  {id:"k06",kind:"Kinky opdrachten",intensity:"Stevig in taal",title:"Vraag en wacht",text:"Vraag om een eenvoudige gunst die eerder is goedgekeurd. Wacht op het antwoord in plaats van het in te vullen. Een weigering is een volledig antwoord."},
  {id:"k07",kind:"Kinky opdrachten",intensity:"Zacht",title:"De belofte",text:"Benoem één afspraak die je vandaag bewust wilt respecteren. Laat de ander bevestigen, aanpassen of afwijzen wat je voorstelt."},
  {id:"k08",kind:"Kinky opdrachten",intensity:"Stevig in taal",title:"De rol kiezen",text:"Kies voor deze ronde een rol of dynamiek die jullie al besproken hebben. Beschrijf in één zin wat die rol vandaag wel en niet betekent."},
  {id:"k09",kind:"Kinky opdrachten",intensity:"Zacht",title:"Stilte op verzoek",text:"Spreek maximaal één minuut stilte af, alleen als dat voor iedereen comfortabel is. Gebruik daarna een check-in: groen, geel of rood."},
  {id:"k10",kind:"Kinky opdrachten",intensity:"Stevig in taal",title:"De grens hardop",text:"Noem één grens die vandaag absoluut blijft staan. De ander herhaalt die grens in eigen woorden, zonder te onderhandelen."},
  {id:"k11",kind:"Kinky opdrachten",intensity:"Zacht",title:"De keuze uit twee",text:"Bied twee veilige, vooraf goedgekeurde opties aan. Laat de ander kiezen of allebei afwijzen."},
  {id:"k12",kind:"Kinky opdrachten",intensity:"Stevig in taal",title:"Compliment op commando",text:"Geef op verzoek één oprecht compliment over een keuze, eigenschap of inspanning. Geen opmerkingen over iemands lichaam tenzij die welkom zijn."},
  {id:"k13",kind:"Kinky opdrachten",intensity:"Zacht",title:"Het teken van vertrouwen",text:"Kies samen een klein voorwerp als symbool van vertrouwen. Leg uit wat het voor jou betekent en spreek af wanneer je het weglegt."},
  {id:"k14",kind:"Kinky opdrachten",intensity:"Stevig in taal",title:"De check-in leiden",text:"Neem de leiding in een korte check-in: vraag naar groen, geel of rood, luister naar het antwoord en pas het plan aan zonder druk."},
  {id:"q01",kind:"Kinky vragen",intensity:"Reflectie",title:"Wat betekent overgave?",text:"Wanneer voelt overgave voor jou als een vrije keuze, en wat zou die vrijheid direct wegnemen?"},
  {id:"q02",kind:"Kinky vragen",intensity:"Reflectie",title:"De taal van macht",text:"Welke woorden of aanspreekvormen voelen spannend en welkom? Welke woorden zijn een harde nee?"},
  {id:"q03",kind:"Kinky vragen",intensity:"Reflectie",title:"Leiden met zorg",text:"Waaraan merk je dat iemand verantwoordelijkheid neemt zonder jouw keuzes over te nemen?"},
  {id:"q04",kind:"Kinky vragen",intensity:"Reflectie",title:"Speelse weerstand",text:"Welke vormen van plagen of uitdagende taal zijn leuk voor jou, en welke zouden echt kwetsend voelen?"},
  {id:"q05",kind:"Kinky vragen",intensity:"Reflectie",title:"Een grens die veranderde",text:"Is er iets waar je nieuwsgierig naar bent maar nog niet klaar voor bent? Wat zou je nodig hebben om er veilig over te praten?"},
  {id:"q06",kind:"Kinky vragen",intensity:"Reflectie",title:"De kracht van nee",text:"Wat helpt jou om zonder schuldgevoel nee te zeggen, ook wanneer de ander enthousiast is?"},
  {id:"q07",kind:"Kinky vragen",intensity:"Reflectie",title:"De nasleep",text:"Welke vorm van aftercare helpt je het meest: praten, stilte, warmte, ruimte of iets anders?"},
  {id:"q08",kind:"Kinky vragen",intensity:"Reflectie",title:"Een fantasie bespreken",text:"Welke fantasie zou je eerst alleen willen bespreken, zonder verwachting dat je die ooit uitvoert?"},
  {id:"q09",kind:"Kinky vragen",intensity:"Reflectie",title:"Vertrouwen verdienen",text:"Welke kleine, herhaalbare actie bouwt voor jou meer vertrouwen op dan grote beloften?"},
  {id:"q10",kind:"Kinky vragen",intensity:"Reflectie",title:"De rode lijn",text:"Welke grens wil je dat de ander onthoudt, ook als je die niet iedere keer opnieuw benoemt?"},
  {id:"v01",kind:"Vanille & verbinding",intensity:"Zacht",title:"Twee minuten aandacht",text:"Leg schermen weg en geef elkaar twee minuten onverdeelde aandacht. Je hoeft niets op te lossen of te presteren."},
  {id:"v02",kind:"Vanille & verbinding",intensity:"Zacht",title:"Kies de soundtrack",text:"Kies ieder één nummer dat je stemming beschrijft. Luister samen en vertel waarom je het koos."},
  {id:"v03",kind:"Vanille & verbinding",intensity:"Reflectie",title:"Een kleine waardering",text:"Noem iets kleins dat de ander recent deed en dat je waardeerde. Houd het concreet en oprecht."},
  {id:"v04",kind:"Vanille & verbinding",intensity:"Zacht",title:"De mini-date",text:"Bedenk samen een date van maximaal twintig minuten die weinig kost en voor beiden prettig voelt."},
  {id:"v05",kind:"Vanille & verbinding",intensity:"Reflectie",title:"Wat heb je nodig?",text:"Maak deze zin af: 'Ik voel me vandaag gesteund wanneer…' Luister zonder meteen advies te geven."},
  {id:"v06",kind:"Vanille & verbinding",intensity:"Zacht",title:"Een keuze cadeau",text:"Laat de ander kiezen tussen twee kleine activiteiten. Respecteer de keuze, ook als die anders is dan je eigen voorkeur."},
  {id:"v07",kind:"Vanille & verbinding",intensity:"Reflectie",title:"Samen groeien",text:"Welke gewoonte zou je samen willen opbouwen, en wat is de kleinste haalbare eerste stap?"},
  {id:"v08",kind:"Vanille & verbinding",intensity:"Zacht",title:"Een vriendelijk bericht",text:"Schrijf een kort bericht waarin je benoemt wat je aan de ander waardeert. Versturen is optioneel."},
  {id:"a01",kind:"Aftercare",intensity:"Zacht",title:"Groen, geel of rood?",text:"Check in zonder aannames: groen betekent oké, geel betekent vertragen en afstemmen, rood betekent onmiddellijk stoppen."},
  {id:"a02",kind:"Aftercare",intensity:"Reflectie",title:"Wat landt goed?",text:"Kies wat je nu nodig hebt: water, warmte, stilte, een gesprek, ruimte of praktische hulp. Je hoeft geen uitleg te geven."},
  {id:"a03",kind:"Aftercare",intensity:"Reflectie",title:"Geen evaluatieplicht",text:"Je hoeft niet meteen te analyseren. Spreek af of je nu, later of helemaal niet wilt napraten."},
  {id:"a04",kind:"Aftercare",intensity:"Zacht",title:"De volgende dag",text:"Plan een vrijblijvende check-in voor later: 'Hoe voel je je nu terugkijkend, en is er iets dat je nodig hebt?'"},
  {id:"a05",kind:"Aftercare",intensity:"Reflectie",title:"Wat nemen we mee?",text:"Noem één ding dat goed voelde en één ding dat je volgende keer anders wilt. Allebei mogen ook passen."},
  {id:"k15",kind:"Kinky opdrachten",intensity:"Stevig in taal",title:"Protocol op maat",text:"Kies samen één klein protocol voor deze ronde, zoals eerst vragen en dan handelen. Spreek af wanneer het geldt en wanneer je het mag onderbreken."},
  {id:"k16",kind:"Kinky opdrachten",intensity:"Stevig in taal",title:"De aanspreekvorm",text:"Vraag of een afgesproken titel of aanspreekvorm vandaag welkom is. Gebruik die alleen na een duidelijk ja en stop meteen als het niet meer goed voelt."},
  {id:"k17",kind:"Kinky opdrachten",intensity:"Zacht",title:"Dienstbaarheid, zelf gekozen",text:"Kies een kleine attentie of servicehandeling die de ander echt waardeert. Vraag eerst wat welkom is en maak er geen verplichting van."},
  {id:"k18",kind:"Kinky opdrachten",intensity:"Stevig in taal",title:"De speelse uitdaging",text:"Bied een speelse, vooraf goedgekeurde uitdaging aan. De ander mag de uitdaging aannemen, aanpassen of overslaan zonder straf of schuldgevoel."},
  {id:"k19",kind:"Kinky opdrachten",intensity:"Stevig in taal",title:"De grens van plagen",text:"Spreek één soort plagerige taal af die welkom is en één onderwerp dat verboden terrein blijft. Check daarna of de afspraak nog goed voelt."},
  {id:"k20",kind:"Kinky opdrachten",intensity:"Zacht",title:"Regie overdragen",text:"Laat de ander voor één kleine, veilige keuze de regie nemen, zoals muziek of volgorde. Je kunt de keuze altijd terugnemen of opnieuw afstemmen."},
  {id:"q11",kind:"Kinky vragen",intensity:"Reflectie",title:"Dominantie zonder druk",text:"Welke vorm van dominante taal voelt aantrekkelijk, en waaraan merk je dat het omslaat van spannend naar onprettig?"},
  {id:"q12",kind:"Kinky vragen",intensity:"Reflectie",title:"Overgave met grenzen",text:"Wat helpt je om controle vrijwillig uit handen te geven, terwijl je weet dat je die altijd terug kunt nemen?"},
  {id:"q13",kind:"Kinky vragen",intensity:"Reflectie",title:"Regels die werken",text:"Welke afspraak maakt een power dynamic leuker of duidelijker? Welke regel zou juist te beperkend voelen?"},
  {id:"q14",kind:"Kinky vragen",intensity:"Reflectie",title:"Fantasie versus werkelijkheid",text:"Welke fantasie vind je prettig om over te praten, maar wil je niet uitvoeren? Allebei mogen waar zijn."},
  {id:"q15",kind:"Kinky vragen",intensity:"Reflectie",title:"Herstel van vertrouwen",text:"Wat zou je nodig hebben als een afspraak per ongeluk wordt gemist, en hoe kan iemand verantwoordelijkheid nemen zonder je onder druk te zetten?"},
];

const kinds: Array<"Alles" | PromptKind> = ["Alles","Kinky opdrachten","Kinky vragen","Vanille & verbinding","Aftercare"];

type GameRound = { title: string; setup: string; task: string; debrief: string };
type ExperienceGame = { id: string; title: string; subtitle: string; level: string; duration: string; description: string; rounds: GameRound[] };
const experienceGames: ExperienceGame[] = [
 {id:"protocol",title:"The Protocol",subtitle:"Power exchange · Beginner",level:"Beginner",duration:"20–30 min",description:"Bouw een duidelijke D/s-dynamiek op met afgesproken aanspreekvormen, opdrachten en een bewust einde.",rounds:[
  {title:"01 · The Contract",setup:"Ga tegenover elkaar zitten. De leidende partner leest de afspraken rustig voor; de ontvangende partner mag elke regel wijzigen of weigeren.",task:"Spreek één aanspreekvorm, één gewenste vorm van leiding en twee grenzen af. Kies ook een stopwoord en een non-verbaal stopsignaal. Laat ieder de afspraken in eigen woorden herhalen.",debrief:"Vraag: voelt dit als een vrije keuze? Verander of schrap alles waar twijfel over bestaat."},
  {title:"02 · The First Instruction",setup:"De leidende partner gebruikt een kalme, duidelijke stem. Geen geschreeuw, vernedering of onverwachte aanrakingen.",task:"Geef maximaal drie concrete, niet-fysieke opdrachten binnen de afgesproken grenzen, bijvoorbeeld: leg je telefoon weg, kies de soundtrack en beschrijf welke rol je vandaag wilt aannemen. Na elke opdracht wacht je op een duidelijk akkoord.",debrief:"Bespreek welke toon en formulering prettig, spannend of juist niet passend voelde. Een opdracht overslaan heeft geen straf of consequentie."},
  {title:"03 · The Protocol",setup:"Kies samen één klein ritueel, zoals toestemming vragen vóór een volgende stap of een afgesproken begroeting.",task:"Voer het ritueel drie keer rustig uit. De leidende partner checkt tussendoor: groen, geel of rood? Geel betekent pauzeren en heronderhandelen; rood betekent direct stoppen.",debrief:"Beëindig de rollen bewust. Kies aftercare: water, stilte, een gesprek of ruimte. Leg vast wat je volgende keer wilt behouden of aanpassen."}
 ]},
 {id:"command",title:"The Command Room",subtitle:"Dominant language · Intermediate",level:"Intermediate",duration:"25–35 min",description:"Oefen met dominante taal, duidelijke opdrachten en vrijwillige overgave zonder druk of onverwachte escalatie.",rounds:[
  {title:"01 · Set the Tone",setup:"Kies vooraf welke aanspreekvormen en soorten dominante taal welkom zijn. Noteer verboden woorden of thema's.",task:"De leidende partner zegt drie korte, zelfverzekerde zinnen die binnen de afspraken vallen. De ontvangende partner geeft na elke zin feedback met groen, geel of rood. Geen enkele zin verplicht tot een handeling.",debrief:"Welke woorden gaven de gewenste sfeer? Welke woorden moeten uit het script blijven?"},
  {title:"02 · Three Commands",setup:"Kies alleen al goedgekeurde, alledaagse en risicoloze opdrachten. Spreek af dat 'pass' altijd voldoende is.",task:"Geef om de beurt maximaal drie opdrachten, zoals: kies een nummer, ga op een comfortabele plek zitten of beschrijf één behoefte. Wacht na iedere opdracht op een expliciet ja. Accepteer een nee direct en zonder discussie.",debrief:"Bespreek tempo, toon en keuzevrijheid. Was er ergens druk, verwarring of een onverwachte verwachting? Pas het script aan."},
  {title:"03 · Reclaim the Choice",setup:"De ontvangende partner krijgt bewust de regie terug.",task:"De ontvangende partner kiest hoe de scène eindigt: afronden, een rustige check-in doen of stoppen. De leidende partner bevestigt de keuze en bedankt voor de duidelijke communicatie.",debrief:"Sluit af met aftercare en een korte check-in later. Geen punten of beloningen worden toegekend voor het negeren van grenzen."}
 ]},
 {id:"service",title:"The Service Ritual",subtitle:"Service & devotion · Beginner",level:"Beginner",duration:"15–25 min",description:"Maak van vrijwillige dienstbaarheid een persoonlijk ritueel met aandacht, keuze en duidelijke waardering.",rounds:[
  {title:"01 · What Service Means",setup:"Iedereen benoemt wat dienstbaarheid voor hem of haar betekent en wat nadrukkelijk niet gewenst is.",task:"De ontvangende partner kiest één van twee vooraf afgesproken, eenvoudige gebaren, bijvoorbeeld de muziek kiezen of een drankje klaarzetten. De ander vraagt eerst toestemming en voert alleen de gekozen taak uit.",debrief:"Was de taak attent en welkom? Vermijd aannames dat een rol automatisch toegang of gehoorzaamheid geeft."},
  {title:"02 · The Presentation",setup:"Kies een optioneel presentatie- of begroetingsritueel, zoals een buiging, een formele zin of een moment stilte.",task:"Voer het ritueel uit en spreek daarna ieder één zin uit: wat voelde passend en wat wil je veranderen? Herhaal alleen als iedereen dat wil.",debrief:"Een ritueel is een gezamenlijke afspraak, geen verplichting buiten de afgesproken context."},
  {title:"03 · Recognition",setup:"De leidende partner erkent de aandacht en inzet; de ontvangende partner mag aangeven hoe waardering prettig voelt.",task:"Geef één concreet compliment over de zorg, communicatie of aandacht die je zag. Wissel daarna van rol of sluit de ervaring af.",debrief:"Kies aftercare en benoem één ding dat je waardeerde. Vraag toestemming voordat je persoonlijke feedback deelt of bewaart."}
 ]},
 {id:"trust",title:"The Trust Exercise",subtitle:"Boundaries & connection · All levels",level:"All levels",duration:"20–30 min",description:"Een intensieve gespreksgame waarin grenzen, spanning en vertrouwen expliciet worden gemaakt voordat je iets uitvoert.",rounds:[
  {title:"01 · Green / Amber / Red",setup:"Iedereen kiest een stopwoord en een non-verbaal signaal dat ook werkt als spreken lastig wordt.",task:"Noem om de beurt drie categorieën: welkom, misschien na overleg en niet toegestaan. De ander vat samen zonder te onderhandelen. Elke twijfel blijft buiten de scène.",debrief:"Controleer of de lijst klopt en makkelijk terug te vinden is. Geen toestemming betekent niet doorgaan."},
  {title:"02 · The Scenario",setup:"Kies een fictieve, niet-fysieke D/s-situatie, bijvoorbeeld een formeel protocol of een rollenspel met opdrachten.",task:"Speel de situatie twee minuten na met alleen vooraf goedgekeurde taal en eenvoudige handelingen. Stop halverwege bewust voor een check-in en vraag wat aangepast moet worden.",debrief:"Benoem het verschil tussen fantasie, toestemming voor een specifieke handeling en toestemming voor iets anders."},
  {title:"03 · Close with Care",setup:"Laat de rollen los en spreek elkaar weer als gelijken aan.",task:"Iedereen maakt de zin af: 'Op dit moment heb ik behoefte aan…' Kies samen water, rust, praten of ruimte. Plan alleen een vervolg als dat voor beiden welkom is.",debrief:"Een check-in achteraf is geen beoordeling. Geef ruimte voor gemengde gevoelens en verander toekomstige afspraken waar nodig."}
 ]},
 {id:"camera-director",title:"The Camera Director",subtitle:"Photo & video challenges · Intermediate",level:"Intermediate",duration:"15–30 min",description:"Maak een private, cinematic foto- of videoprompt met regie, poses, details en een duidelijke opt-out. Niets wordt automatisch opgenomen of gedeeld.",rounds:[
  {title:"01 · The Frame",setup:"Bespreek eerst wat gefotografeerd mag worden, welke lichaamsdelen of details buiten beeld blijven en of het materiaal uitsluitend privé blijft. Camera blijft uit tot iedereen ja zegt.",task:"De Dom geeft een concrete regie-opdracht: 'Kies een plek met zacht licht. Zet het object of detail dat we hebben afgesproken in beeld. Maak één testfoto van de compositie, zonder herkenbare of intieme details tenzij die expliciet zijn afgesproken.' Bekijk de foto samen en kies bewaren of direct verwijderen.",debrief:"Vraag of de regie prettig voelde en of het beeld binnen de afspraken bleef. Geen foto betekent ook een volwaardige deelname."},
  {title:"02 · The 10-Second Scene",setup:"Kies samen een volledig geklede, niet-expliciete scène: een silhouet, handen die een lint vasthouden, een sleutel, laarzen, handschoenen of een detail van een outfit. Geen gezicht of herkenbare achtergrond zonder expliciete toestemming.",task:"Maak optioneel een clip van maximaal 10 seconden. De Dom geeft drie regie-aanwijzingen: 'Kies je startpositie', 'Beweeg langzaam naar het afgesproken detail' en 'Eindig stil in het licht'. Eerst test je zonder opname; daarna pas opnemen als iedereen opnieuw akkoord is. Geen verborgen opname en geen automatische upload.",debrief:"Bekijk de clip samen, zonder druk om hem te bewaren. Kies privé bewaren, opnieuw opnemen of verwijderen. Deel of upload nooit zonder aparte, expliciete toestemming van iedereen die herkenbaar is."},
  {title:"03 · The Private Premiere",setup:"Iedereen behoudt zeggenschap over eigen beeld, stem, kleding, herkenbaarheid en opslag. Spreek af wie het bestand kan zien en wanneer het wordt verwijderd.",task:"Kies één van drie opties: alleen bekijken op het toestel, bewaren in een afgeschermde privéruimte als die beschikbaar is, of definitief verwijderen. Geef elkaar één compliment over creativiteit of regie, niet over uiterlijk tenzij dat welkom is.",debrief:"Check: voelde de opname vrijwillig en veilig? Leg vast dat toestemming voor maken geen toestemming voor uploaden, delen of hergebruik betekent."}
 ]},
 {id:"ai-dom",title:"AI Dom · The Director",subtitle:"AI-led roleplay · Personalised prompts",level:"Adaptive",duration:"10–30 min",description:"Een dominante AI-persona geeft duidelijke, aanpasbare opdrachten en reageert op je gekozen intensiteit. Dit is de begeleide game-ervaring; live AI-chat vereist een aangesloten AI-backend.",rounds:[
  {title:"01 · Choose Your Dynamic",setup:"Kies de gewenste aanspreekvorm, toon (kalm, streng of plagerig), intensiteit en onderwerpen die verboden terrein zijn. Stel stopwoord en pauze-/stopknop in voordat de rol begint.",task:"AI Dom opent met: 'Welkom. Jij kiest de grenzen; ik geef de richting. Kies je toon en intensiteit, en vertel me wat vandaag buiten de scène blijft.' Selecteer alleen wat bij je past. Geen keuze wordt als toestemming geïnterpreteerd.",debrief:"Controleer de instellingen. Als een onderwerp niet expliciet is goedgekeurd, blijft het buiten het spel."},
  {title:"02 · The Command Sequence",setup:"De Dom-rol gebruikt alleen de vooraf gekozen toon en goedgekeurde onderwerpen. Iedere opdracht moet overslaanbaar zijn.",task:"Voorbeeldscript: 'Sta even stil en kies je houding als dat comfortabel voelt. Beschrijf daarna in één zin wat je van deze scène verwacht.' Volgende stap: 'Kies één van mijn twee veilige opdrachten, of zeg PASS.' De speler kan aanpassen, pauzeren of stoppen; er volgt geen straf voor grenzen.",debrief:"Na elke opdracht kiest de speler groen, geel of rood. Geel pauzeert de scène voor aanpassing; rood beëindigt de scène onmiddellijk."},
  {title:"03 · The Debrief",setup:"De AI Dom verlaat de rol zodra de speler op Stop drukt of de ronde eindigt.",task:"Afsluitende tekst: 'De scène is voorbij. Je hoeft niets te bewijzen. Wil je rust, een korte reflectie of de ervaring afsluiten zonder vragen?' Kies aftercare en geef alleen feedback die je wilt delen.",debrief:"Een echte AI Dom-chat moet server-side grenzen, leeftijdspoort, consent-instellingen en stopcontrole gebruiken. Deze voorbeeldscène doet niet alsof live AI of opgeslagen chat al is aangesloten."}
 ]}

];


export default function PromptLibrary({ onBack, onComplete }: { onBack: () => void; onComplete: () => void }) {
  const [kind, setKind] = useState<(typeof kinds)[number]>("Alles");
  const [mode, setMode] = useState<"games" | "cards">("games");
  const [activeGame, setActiveGame] = useState<string | null>(null);
  const [gameRound, setGameRound] = useState(0);
  const [index, setIndex] = useState(0);
  const [saved, setSaved] = useState<string[]>([]);
  const [copied, setCopied] = useState(false);
  const [completed, setCompleted] = useState<string[]>([]);
  const pool = useMemo(() => prompts.filter((item) => kind === "Alles" || item.kind === kind), [kind]);
  const current = pool[index % Math.max(1, pool.length)];

  const changeKind = (next: (typeof kinds)[number]) => { setKind(next); setIndex(0); setCopied(false); };
  const next = () => { setIndex((value) => pool.length > 1 ? (value + 1 + Math.floor(Math.random() * (pool.length - 1))) % pool.length : 0); setCopied(false); };
  const toggleSaved = () => setSaved((items) => items.includes(current.id) ? items.filter((id) => id !== current.id) : [...items, current.id]);
  const copy = async () => {
    try { await navigator.clipboard.writeText(`AFTER HOURS · ${current.kind.toUpperCase()}\n${current.title}\n\n${current.text}\n\nAlleen met vrije, expliciete en herroepbare toestemming.`); setCopied(true); }
    catch { setCopied(false); }
  };

  return <main className="prompt-library">
    <section className="prompt-hero"><span className="eyebrow">AFTER HOURS · THE DECK</span><h2>Choose your tension.</h2><p>Van zachte verbinding tot duidelijke power dynamics. Jij kiest wat past, wat niet past en wanneer je stopt.</p>
      <div className="prompt-filters" role="group" aria-label="Kies weergave"><button className={mode === "games" ? "active" : ""} onClick={() => {setMode("games");setActiveGame(null)}}>Complete games</button><button className={mode === "cards" ? "active" : ""} onClick={() => {setMode("cards");setActiveGame(null)}}>Losse kaarten</button></div>{mode === "cards" && <div className="prompt-filters" role="group" aria-label="Filter opdrachten">{kinds.map((item) => <button key={item} className={kind === item ? "active" : ""} onClick={() => changeKind(item)}>{item}</button>)}</div>}
    </section>
    {mode === "games" ? <section className="experience-catalog">
      {!activeGame ? <><div className="experience-intro"><span className="eyebrow">THE EXPERIENCE COLLECTION</span><h3>Choose your game.</h3><p>Volledige, begeleide scenario's met drie rondes, concrete opdrachten en een bewuste afsluiting. Alle deelnemers zijn 18+, stemmen vrij in en mogen op ieder moment passen of stoppen.</p></div>
        <div className="experience-grid">{experienceGames.map((game) => <article className="prompt-card experience-card" key={game.id}><div className="prompt-card-top"><span className="eyebrow">{game.subtitle}</span><span className="prompt-intensity">{game.duration}</span></div><div className="prompt-glyph" aria-hidden="true">✦</div><h3>{game.title}</h3><p>{game.description}</p><div className="prompt-consent"><ShieldCheck/><span>{game.rounds.length} rounds · Consent-first · {game.level}</span></div><button className="gold" onClick={() => {setActiveGame(game.id);setGameRound(0)}}><ArrowRight/> Start preview</button></article>)}</div>
      </> : (() => { const game = experienceGames.find((item) => item.id === activeGame)!; const round = game.rounds[gameRound]; return <article className="prompt-card experience-play"><div className="prompt-card-top"><span className="eyebrow">{game.title}</span><span className="prompt-intensity">ROUND {gameRound + 1} / {game.rounds.length}</span></div><div className="prompt-glyph" aria-hidden="true">✦</div><h3>{round.title}</h3><p><strong>SET THE SCENE</strong><br/>{round.setup}</p><p><strong>YOUR ASSIGNMENT</strong><br/>{round.task}</p><p><strong>CHECK-IN & DEBRIEF</strong><br/>{round.debrief}</p><div className="prompt-consent"><ShieldCheck/><span>Stopwoord en non-verbaal signaal blijven actief. Geel = pauze en afstemmen. Rood = direct stoppen.</span></div><div className="prompt-actions"><button onClick={() => {setActiveGame(null);setGameRound(0)}}>Exit game</button>{gameRound < game.rounds.length - 1 ? <button className="gold" onClick={() => setGameRound((value) => value + 1)}><ArrowRight/> Next round</button> : <button className="gold" onClick={() => {setActiveGame(null);setGameRound(0);onComplete()}}><Check/> Complete experience</button>}</div></article>; })()}
    </section> : <>
    <section className="prompt-card">
      <div className="prompt-card-top"><span className="eyebrow">{current.kind.toUpperCase()}</span><span className="prompt-intensity">{current.intensity}</span></div>
      <div className="prompt-glyph" aria-hidden="true">✦</div><h3>{current.title}</h3><p>{current.text}</p>
      {current.note && <p className="prompt-note">{current.note}</p>}
      <div className="prompt-consent"><ShieldCheck/><span>18+ · Vrijwillig · Je mag altijd passen of stoppen.</span></div>
      <div className="prompt-actions"><button className="gold" onClick={next}><Shuffle/> Volgende kaart</button><button onClick={toggleSaved}><Heart fill={saved.includes(current.id) ? "currentColor" : "none"}/>{saved.includes(current.id) ? "Bewaard" : "Bewaar"}</button><button onClick={() => { if (!completed.includes(current.id)) { setCompleted((items) => [...items, current.id]); onComplete(); } }}>{completed.includes(current.id) ? <Check/> : <ArrowRight/>}{completed.includes(current.id) ? "Gedaan" : "Markeer gedaan"}</button><button onClick={() => void copy()}>{copied ? <Check/> : <Copy/>}{copied ? "Gekopieerd" : "Kopieer"}</button></div>
    </section>

    </>}
    {mode === "cards" && <section className="prompt-count"><span>{pool.length} kaarten in deze selectie</span><span>{saved.length} lokaal bewaard</span></section>}
    <button className="prompt-back" onClick={onBack}><ArrowRight/> Terug</button>
  </main>;
}
